version: '3'
services:
  elasticsearch:
    build: "./elasticsearch"
    image: "chatbot_es:develop"
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - "chatbot_es:/usr/share/elasticsearch/data"
      - "./elasticsearch/config/analyzer:/usr/share/elasticsearch/config/analyzer"
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: chatbot_es
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.4"
    ports:
      - "15601:5601"
    links:
      - elasticsearch:elasticsearch
  db:
    image: "postgres:10"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/chatbot
    volumes:
      - chatbot_db:/var/lib/postgresql/data/chatbot
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
    container_name: chatbot_db
volumes:
  chatbot_db:
  chatbot_es: