version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Resolve submodules
          command: git submodule update --init --recursive

      - restore_cache:
          keys:
            - stack-executable
            - stack

      - run:
          name: Install Stack
          command: .circleci/install-stack.sh

      - run:
          name: Install libpq
          command: sudo apt-get install -y libpq-dev

      - save_cache:
          key: stack-executable
          paths:
            - ~/.local/bin/stack

      - run:
          name: Start containers
          command: docker-compose up -d

      - run:
          name: Build & Test
          command: |
            cd chatbot
            ~/.local/bin/stack --install-ghc test --only-dependencies
            ~/.local/bin/stack test

      - save_cache:
          key: stack
          paths:
            - ~/.stack