version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-executable
            - stack

      - run:
          name: Install Stack
          command: .circleci/install-stack.sh

      - save_cache:
          key: stack-executable
          paths:
            - ~/.local/bin/stack

      - run:
          name: Start containers
          command: docker-compose up -d

      - run:
          name: Build & Test
          working_directory: ${CIRCLE_WORKING_DIRECTORY}/chatbot
          command: ~/.local/bin/stack --install-ghc test --only-dependencies
          command: ~/.local/bin/stack test

      - save_cache:
          key: stack
          paths:
            - ~/.stack