name:                chatbot
version:             0.1.0.0
github:              "githubuser/chatbot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/chatbot#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- transformers
- time
- exceptions
- bytestring
- case-insensitive
- aeson
- lens
- extensible
- http-types
- http-conduit
- hs-graph
- hs-resource
- hs-orm

default-extensions:
  - DataKinds
  - TypeOperators
  - KindSignatures
  - TypeFamilies
  - FlexibleContexts
  - FlexibleInstances
  - TypeApplications
  - MultiParamTypeClasses
  - ImplicitParams

library:
  source-dirs: src

executables:
  chatbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatbot

tests:
  chatbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatbot
